## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - nightly
notifications:
  email: false
git:
  depth: 99999999

before_script:
  # Grab our custom version of julia
  - curl -A "$CURL_USER_AGENT" -s -L --retry 7 https://storage.googleapis.com/julia-tpu-binaries/julia.v1.1.0-kf.tpu3.x86_64-linux-gnu.tar.gz | tar -C ~/julia -x -z -f -
  - julia --color=yes -e "using InteractiveUtils; versioninfo()"

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("XLA")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("XLA")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
