// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/compiler/xla/service/hlo_profile_printer_data.proto

#ifndef PROTOBUF_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto_INCLUDED
#define PROTOBUF_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto_INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsHloProfilePrinterData_HloInstructionInfoImpl();
void InitDefaultsHloProfilePrinterData_HloInstructionInfo();
void InitDefaultsHloProfilePrinterData_HloComputationInfoImpl();
void InitDefaultsHloProfilePrinterData_HloComputationInfo();
void InitDefaultsHloProfilePrinterDataImpl();
void InitDefaultsHloProfilePrinterData();
inline void InitDefaults() {
  InitDefaultsHloProfilePrinterData_HloInstructionInfo();
  InitDefaultsHloProfilePrinterData_HloComputationInfo();
  InitDefaultsHloProfilePrinterData();
}
}  // namespace protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto
namespace xla {
class HloProfilePrinterData;
class HloProfilePrinterDataDefaultTypeInternal;
extern HloProfilePrinterDataDefaultTypeInternal _HloProfilePrinterData_default_instance_;
class HloProfilePrinterData_HloComputationInfo;
class HloProfilePrinterData_HloComputationInfoDefaultTypeInternal;
extern HloProfilePrinterData_HloComputationInfoDefaultTypeInternal _HloProfilePrinterData_HloComputationInfo_default_instance_;
class HloProfilePrinterData_HloInstructionInfo;
class HloProfilePrinterData_HloInstructionInfoDefaultTypeInternal;
extern HloProfilePrinterData_HloInstructionInfoDefaultTypeInternal _HloProfilePrinterData_HloInstructionInfo_default_instance_;
}  // namespace xla
namespace google {
namespace protobuf {
template<> ::xla::HloProfilePrinterData* Arena::CreateMessage< ::xla::HloProfilePrinterData>(Arena*);
template<> ::xla::HloProfilePrinterData_HloComputationInfo* Arena::CreateMessage< ::xla::HloProfilePrinterData_HloComputationInfo>(Arena*);
template<> ::xla::HloProfilePrinterData_HloInstructionInfo* Arena::CreateMessage< ::xla::HloProfilePrinterData_HloInstructionInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace xla {

// ===================================================================

class HloProfilePrinterData_HloInstructionInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xla.HloProfilePrinterData.HloInstructionInfo) */ {
 public:
  HloProfilePrinterData_HloInstructionInfo();
  virtual ~HloProfilePrinterData_HloInstructionInfo();

  HloProfilePrinterData_HloInstructionInfo(const HloProfilePrinterData_HloInstructionInfo& from);

  inline HloProfilePrinterData_HloInstructionInfo& operator=(const HloProfilePrinterData_HloInstructionInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HloProfilePrinterData_HloInstructionInfo(HloProfilePrinterData_HloInstructionInfo&& from) noexcept
    : HloProfilePrinterData_HloInstructionInfo() {
    *this = ::std::move(from);
  }

  inline HloProfilePrinterData_HloInstructionInfo& operator=(HloProfilePrinterData_HloInstructionInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const HloProfilePrinterData_HloInstructionInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HloProfilePrinterData_HloInstructionInfo* internal_default_instance() {
    return reinterpret_cast<const HloProfilePrinterData_HloInstructionInfo*>(
               &_HloProfilePrinterData_HloInstructionInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(HloProfilePrinterData_HloInstructionInfo* other);
  void Swap(HloProfilePrinterData_HloInstructionInfo* other);
  friend void swap(HloProfilePrinterData_HloInstructionInfo& a, HloProfilePrinterData_HloInstructionInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HloProfilePrinterData_HloInstructionInfo* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::CreateMessage<HloProfilePrinterData_HloInstructionInfo>(NULL);
  }

  HloProfilePrinterData_HloInstructionInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::CreateMessage<HloProfilePrinterData_HloInstructionInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HloProfilePrinterData_HloInstructionInfo& from);
  void MergeFrom(const HloProfilePrinterData_HloInstructionInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HloProfilePrinterData_HloInstructionInfo* other);
  protected:
  explicit HloProfilePrinterData_HloInstructionInfo(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string long_name = 1;
  void clear_long_name();
  static const int kLongNameFieldNumber = 1;
  const ::std::string& long_name() const;
  void set_long_name(const ::std::string& value);
  #if LANG_CXX11
  void set_long_name(::std::string&& value);
  #endif
  void set_long_name(const char* value);
  void set_long_name(const char* value, size_t size);
  ::std::string* mutable_long_name();
  ::std::string* release_long_name();
  void set_allocated_long_name(::std::string* long_name);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_long_name();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_long_name(
      ::std::string* long_name);

  // string short_name = 2;
  void clear_short_name();
  static const int kShortNameFieldNumber = 2;
  const ::std::string& short_name() const;
  void set_short_name(const ::std::string& value);
  #if LANG_CXX11
  void set_short_name(::std::string&& value);
  #endif
  void set_short_name(const char* value);
  void set_short_name(const char* value, size_t size);
  ::std::string* mutable_short_name();
  ::std::string* release_short_name();
  void set_allocated_short_name(::std::string* short_name);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_short_name();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_short_name(
      ::std::string* short_name);

  // string category = 3;
  void clear_category();
  static const int kCategoryFieldNumber = 3;
  const ::std::string& category() const;
  void set_category(const ::std::string& value);
  #if LANG_CXX11
  void set_category(::std::string&& value);
  #endif
  void set_category(const char* value);
  void set_category(const char* value, size_t size);
  ::std::string* mutable_category();
  ::std::string* release_category();
  void set_allocated_category(::std::string* category);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_category();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_category(
      ::std::string* category);

  // float flop_count = 4;
  void clear_flop_count();
  static const int kFlopCountFieldNumber = 4;
  float flop_count() const;
  void set_flop_count(float value);

  // float transcendental_count = 5;
  void clear_transcendental_count();
  static const int kTranscendentalCountFieldNumber = 5;
  float transcendental_count() const;
  void set_transcendental_count(float value);

  // float bytes_accessed = 6;
  void clear_bytes_accessed();
  static const int kBytesAccessedFieldNumber = 6;
  float bytes_accessed() const;
  void set_bytes_accessed(float value);

  // float optimal_seconds = 7;
  void clear_optimal_seconds();
  static const int kOptimalSecondsFieldNumber = 7;
  float optimal_seconds() const;
  void set_optimal_seconds(float value);

  // int64 profile_index = 8;
  void clear_profile_index();
  static const int kProfileIndexFieldNumber = 8;
  ::google::protobuf::int64 profile_index() const;
  void set_profile_index(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:xla.HloProfilePrinterData.HloInstructionInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::ArenaStringPtr long_name_;
  ::google::protobuf::internal::ArenaStringPtr short_name_;
  ::google::protobuf::internal::ArenaStringPtr category_;
  float flop_count_;
  float transcendental_count_;
  float bytes_accessed_;
  float optimal_seconds_;
  ::google::protobuf::int64 profile_index_;
  mutable int _cached_size_;
  friend struct ::protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto::TableStruct;
  friend void ::protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto::InitDefaultsHloProfilePrinterData_HloInstructionInfoImpl();
};
// -------------------------------------------------------------------

class HloProfilePrinterData_HloComputationInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xla.HloProfilePrinterData.HloComputationInfo) */ {
 public:
  HloProfilePrinterData_HloComputationInfo();
  virtual ~HloProfilePrinterData_HloComputationInfo();

  HloProfilePrinterData_HloComputationInfo(const HloProfilePrinterData_HloComputationInfo& from);

  inline HloProfilePrinterData_HloComputationInfo& operator=(const HloProfilePrinterData_HloComputationInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HloProfilePrinterData_HloComputationInfo(HloProfilePrinterData_HloComputationInfo&& from) noexcept
    : HloProfilePrinterData_HloComputationInfo() {
    *this = ::std::move(from);
  }

  inline HloProfilePrinterData_HloComputationInfo& operator=(HloProfilePrinterData_HloComputationInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const HloProfilePrinterData_HloComputationInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HloProfilePrinterData_HloComputationInfo* internal_default_instance() {
    return reinterpret_cast<const HloProfilePrinterData_HloComputationInfo*>(
               &_HloProfilePrinterData_HloComputationInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void UnsafeArenaSwap(HloProfilePrinterData_HloComputationInfo* other);
  void Swap(HloProfilePrinterData_HloComputationInfo* other);
  friend void swap(HloProfilePrinterData_HloComputationInfo& a, HloProfilePrinterData_HloComputationInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HloProfilePrinterData_HloComputationInfo* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::CreateMessage<HloProfilePrinterData_HloComputationInfo>(NULL);
  }

  HloProfilePrinterData_HloComputationInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::CreateMessage<HloProfilePrinterData_HloComputationInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HloProfilePrinterData_HloComputationInfo& from);
  void MergeFrom(const HloProfilePrinterData_HloComputationInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HloProfilePrinterData_HloComputationInfo* other);
  protected:
  explicit HloProfilePrinterData_HloComputationInfo(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .xla.HloProfilePrinterData.HloInstructionInfo instruction_infos = 3;
  int instruction_infos_size() const;
  void clear_instruction_infos();
  static const int kInstructionInfosFieldNumber = 3;
  ::xla::HloProfilePrinterData_HloInstructionInfo* mutable_instruction_infos(int index);
  ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloInstructionInfo >*
      mutable_instruction_infos();
  const ::xla::HloProfilePrinterData_HloInstructionInfo& instruction_infos(int index) const;
  ::xla::HloProfilePrinterData_HloInstructionInfo* add_instruction_infos();
  const ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloInstructionInfo >&
      instruction_infos() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_name();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      ::std::string* name);

  // int64 profile_index = 2;
  void clear_profile_index();
  static const int kProfileIndexFieldNumber = 2;
  ::google::protobuf::int64 profile_index() const;
  void set_profile_index(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:xla.HloProfilePrinterData.HloComputationInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloInstructionInfo > instruction_infos_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int64 profile_index_;
  mutable int _cached_size_;
  friend struct ::protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto::TableStruct;
  friend void ::protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto::InitDefaultsHloProfilePrinterData_HloComputationInfoImpl();
};
// -------------------------------------------------------------------

class HloProfilePrinterData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xla.HloProfilePrinterData) */ {
 public:
  HloProfilePrinterData();
  virtual ~HloProfilePrinterData();

  HloProfilePrinterData(const HloProfilePrinterData& from);

  inline HloProfilePrinterData& operator=(const HloProfilePrinterData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HloProfilePrinterData(HloProfilePrinterData&& from) noexcept
    : HloProfilePrinterData() {
    *this = ::std::move(from);
  }

  inline HloProfilePrinterData& operator=(HloProfilePrinterData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const HloProfilePrinterData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HloProfilePrinterData* internal_default_instance() {
    return reinterpret_cast<const HloProfilePrinterData*>(
               &_HloProfilePrinterData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void UnsafeArenaSwap(HloProfilePrinterData* other);
  void Swap(HloProfilePrinterData* other);
  friend void swap(HloProfilePrinterData& a, HloProfilePrinterData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HloProfilePrinterData* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::CreateMessage<HloProfilePrinterData>(NULL);
  }

  HloProfilePrinterData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::CreateMessage<HloProfilePrinterData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HloProfilePrinterData& from);
  void MergeFrom(const HloProfilePrinterData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HloProfilePrinterData* other);
  protected:
  explicit HloProfilePrinterData(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef HloProfilePrinterData_HloInstructionInfo HloInstructionInfo;
  typedef HloProfilePrinterData_HloComputationInfo HloComputationInfo;

  // accessors -------------------------------------------------------

  // repeated .xla.HloProfilePrinterData.HloComputationInfo computation_infos = 1;
  int computation_infos_size() const;
  void clear_computation_infos();
  static const int kComputationInfosFieldNumber = 1;
  ::xla::HloProfilePrinterData_HloComputationInfo* mutable_computation_infos(int index);
  ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloComputationInfo >*
      mutable_computation_infos();
  const ::xla::HloProfilePrinterData_HloComputationInfo& computation_infos(int index) const;
  ::xla::HloProfilePrinterData_HloComputationInfo* add_computation_infos();
  const ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloComputationInfo >&
      computation_infos() const;

  // int64 profile_counters_size = 2;
  void clear_profile_counters_size();
  static const int kProfileCountersSizeFieldNumber = 2;
  ::google::protobuf::int64 profile_counters_size() const;
  void set_profile_counters_size(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:xla.HloProfilePrinterData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloComputationInfo > computation_infos_;
  ::google::protobuf::int64 profile_counters_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto::TableStruct;
  friend void ::protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto::InitDefaultsHloProfilePrinterDataImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HloProfilePrinterData_HloInstructionInfo

// string long_name = 1;
inline void HloProfilePrinterData_HloInstructionInfo::clear_long_name() {
  long_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& HloProfilePrinterData_HloInstructionInfo::long_name() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
  return long_name_.Get();
}
inline void HloProfilePrinterData_HloInstructionInfo::set_long_name(const ::std::string& value) {
  
  long_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
}
#if LANG_CXX11
inline void HloProfilePrinterData_HloInstructionInfo::set_long_name(::std::string&& value) {
  
  long_name_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
}
#endif
inline void HloProfilePrinterData_HloInstructionInfo::set_long_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  long_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
}
inline void HloProfilePrinterData_HloInstructionInfo::set_long_name(const char* value,
    size_t size) {
  
  long_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::mutable_long_name() {
  
  // @@protoc_insertion_point(field_mutable:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
  return long_name_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::release_long_name() {
  // @@protoc_insertion_point(field_release:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
  
  return long_name_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void HloProfilePrinterData_HloInstructionInfo::set_allocated_long_name(::std::string* long_name) {
  if (long_name != NULL) {
    
  } else {
    
  }
  long_name_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), long_name,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::unsafe_arena_release_long_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return long_name_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void HloProfilePrinterData_HloInstructionInfo::unsafe_arena_set_allocated_long_name(
    ::std::string* long_name) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (long_name != NULL) {
    
  } else {
    
  }
  long_name_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      long_name, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:xla.HloProfilePrinterData.HloInstructionInfo.long_name)
}

// string short_name = 2;
inline void HloProfilePrinterData_HloInstructionInfo::clear_short_name() {
  short_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& HloProfilePrinterData_HloInstructionInfo::short_name() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
  return short_name_.Get();
}
inline void HloProfilePrinterData_HloInstructionInfo::set_short_name(const ::std::string& value) {
  
  short_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
}
#if LANG_CXX11
inline void HloProfilePrinterData_HloInstructionInfo::set_short_name(::std::string&& value) {
  
  short_name_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
}
#endif
inline void HloProfilePrinterData_HloInstructionInfo::set_short_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  short_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
}
inline void HloProfilePrinterData_HloInstructionInfo::set_short_name(const char* value,
    size_t size) {
  
  short_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::mutable_short_name() {
  
  // @@protoc_insertion_point(field_mutable:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
  return short_name_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::release_short_name() {
  // @@protoc_insertion_point(field_release:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
  
  return short_name_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void HloProfilePrinterData_HloInstructionInfo::set_allocated_short_name(::std::string* short_name) {
  if (short_name != NULL) {
    
  } else {
    
  }
  short_name_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), short_name,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::unsafe_arena_release_short_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return short_name_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void HloProfilePrinterData_HloInstructionInfo::unsafe_arena_set_allocated_short_name(
    ::std::string* short_name) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (short_name != NULL) {
    
  } else {
    
  }
  short_name_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      short_name, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:xla.HloProfilePrinterData.HloInstructionInfo.short_name)
}

// string category = 3;
inline void HloProfilePrinterData_HloInstructionInfo::clear_category() {
  category_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& HloProfilePrinterData_HloInstructionInfo::category() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloInstructionInfo.category)
  return category_.Get();
}
inline void HloProfilePrinterData_HloInstructionInfo::set_category(const ::std::string& value) {
  
  category_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloInstructionInfo.category)
}
#if LANG_CXX11
inline void HloProfilePrinterData_HloInstructionInfo::set_category(::std::string&& value) {
  
  category_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:xla.HloProfilePrinterData.HloInstructionInfo.category)
}
#endif
inline void HloProfilePrinterData_HloInstructionInfo::set_category(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  category_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:xla.HloProfilePrinterData.HloInstructionInfo.category)
}
inline void HloProfilePrinterData_HloInstructionInfo::set_category(const char* value,
    size_t size) {
  
  category_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:xla.HloProfilePrinterData.HloInstructionInfo.category)
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::mutable_category() {
  
  // @@protoc_insertion_point(field_mutable:xla.HloProfilePrinterData.HloInstructionInfo.category)
  return category_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::release_category() {
  // @@protoc_insertion_point(field_release:xla.HloProfilePrinterData.HloInstructionInfo.category)
  
  return category_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void HloProfilePrinterData_HloInstructionInfo::set_allocated_category(::std::string* category) {
  if (category != NULL) {
    
  } else {
    
  }
  category_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), category,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:xla.HloProfilePrinterData.HloInstructionInfo.category)
}
inline ::std::string* HloProfilePrinterData_HloInstructionInfo::unsafe_arena_release_category() {
  // @@protoc_insertion_point(field_unsafe_arena_release:xla.HloProfilePrinterData.HloInstructionInfo.category)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return category_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void HloProfilePrinterData_HloInstructionInfo::unsafe_arena_set_allocated_category(
    ::std::string* category) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (category != NULL) {
    
  } else {
    
  }
  category_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      category, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:xla.HloProfilePrinterData.HloInstructionInfo.category)
}

// float flop_count = 4;
inline void HloProfilePrinterData_HloInstructionInfo::clear_flop_count() {
  flop_count_ = 0;
}
inline float HloProfilePrinterData_HloInstructionInfo::flop_count() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloInstructionInfo.flop_count)
  return flop_count_;
}
inline void HloProfilePrinterData_HloInstructionInfo::set_flop_count(float value) {
  
  flop_count_ = value;
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloInstructionInfo.flop_count)
}

// float transcendental_count = 5;
inline void HloProfilePrinterData_HloInstructionInfo::clear_transcendental_count() {
  transcendental_count_ = 0;
}
inline float HloProfilePrinterData_HloInstructionInfo::transcendental_count() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloInstructionInfo.transcendental_count)
  return transcendental_count_;
}
inline void HloProfilePrinterData_HloInstructionInfo::set_transcendental_count(float value) {
  
  transcendental_count_ = value;
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloInstructionInfo.transcendental_count)
}

// float bytes_accessed = 6;
inline void HloProfilePrinterData_HloInstructionInfo::clear_bytes_accessed() {
  bytes_accessed_ = 0;
}
inline float HloProfilePrinterData_HloInstructionInfo::bytes_accessed() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloInstructionInfo.bytes_accessed)
  return bytes_accessed_;
}
inline void HloProfilePrinterData_HloInstructionInfo::set_bytes_accessed(float value) {
  
  bytes_accessed_ = value;
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloInstructionInfo.bytes_accessed)
}

// float optimal_seconds = 7;
inline void HloProfilePrinterData_HloInstructionInfo::clear_optimal_seconds() {
  optimal_seconds_ = 0;
}
inline float HloProfilePrinterData_HloInstructionInfo::optimal_seconds() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloInstructionInfo.optimal_seconds)
  return optimal_seconds_;
}
inline void HloProfilePrinterData_HloInstructionInfo::set_optimal_seconds(float value) {
  
  optimal_seconds_ = value;
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloInstructionInfo.optimal_seconds)
}

// int64 profile_index = 8;
inline void HloProfilePrinterData_HloInstructionInfo::clear_profile_index() {
  profile_index_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 HloProfilePrinterData_HloInstructionInfo::profile_index() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloInstructionInfo.profile_index)
  return profile_index_;
}
inline void HloProfilePrinterData_HloInstructionInfo::set_profile_index(::google::protobuf::int64 value) {
  
  profile_index_ = value;
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloInstructionInfo.profile_index)
}

// -------------------------------------------------------------------

// HloProfilePrinterData_HloComputationInfo

// string name = 1;
inline void HloProfilePrinterData_HloComputationInfo::clear_name() {
  name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& HloProfilePrinterData_HloComputationInfo::name() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloComputationInfo.name)
  return name_.Get();
}
inline void HloProfilePrinterData_HloComputationInfo::set_name(const ::std::string& value) {
  
  name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloComputationInfo.name)
}
#if LANG_CXX11
inline void HloProfilePrinterData_HloComputationInfo::set_name(::std::string&& value) {
  
  name_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:xla.HloProfilePrinterData.HloComputationInfo.name)
}
#endif
inline void HloProfilePrinterData_HloComputationInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:xla.HloProfilePrinterData.HloComputationInfo.name)
}
inline void HloProfilePrinterData_HloComputationInfo::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:xla.HloProfilePrinterData.HloComputationInfo.name)
}
inline ::std::string* HloProfilePrinterData_HloComputationInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:xla.HloProfilePrinterData.HloComputationInfo.name)
  return name_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* HloProfilePrinterData_HloComputationInfo::release_name() {
  // @@protoc_insertion_point(field_release:xla.HloProfilePrinterData.HloComputationInfo.name)
  
  return name_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void HloProfilePrinterData_HloComputationInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:xla.HloProfilePrinterData.HloComputationInfo.name)
}
inline ::std::string* HloProfilePrinterData_HloComputationInfo::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:xla.HloProfilePrinterData.HloComputationInfo.name)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return name_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void HloProfilePrinterData_HloComputationInfo::unsafe_arena_set_allocated_name(
    ::std::string* name) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (name != NULL) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      name, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:xla.HloProfilePrinterData.HloComputationInfo.name)
}

// int64 profile_index = 2;
inline void HloProfilePrinterData_HloComputationInfo::clear_profile_index() {
  profile_index_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 HloProfilePrinterData_HloComputationInfo::profile_index() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloComputationInfo.profile_index)
  return profile_index_;
}
inline void HloProfilePrinterData_HloComputationInfo::set_profile_index(::google::protobuf::int64 value) {
  
  profile_index_ = value;
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.HloComputationInfo.profile_index)
}

// repeated .xla.HloProfilePrinterData.HloInstructionInfo instruction_infos = 3;
inline int HloProfilePrinterData_HloComputationInfo::instruction_infos_size() const {
  return instruction_infos_.size();
}
inline void HloProfilePrinterData_HloComputationInfo::clear_instruction_infos() {
  instruction_infos_.Clear();
}
inline ::xla::HloProfilePrinterData_HloInstructionInfo* HloProfilePrinterData_HloComputationInfo::mutable_instruction_infos(int index) {
  // @@protoc_insertion_point(field_mutable:xla.HloProfilePrinterData.HloComputationInfo.instruction_infos)
  return instruction_infos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloInstructionInfo >*
HloProfilePrinterData_HloComputationInfo::mutable_instruction_infos() {
  // @@protoc_insertion_point(field_mutable_list:xla.HloProfilePrinterData.HloComputationInfo.instruction_infos)
  return &instruction_infos_;
}
inline const ::xla::HloProfilePrinterData_HloInstructionInfo& HloProfilePrinterData_HloComputationInfo::instruction_infos(int index) const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.HloComputationInfo.instruction_infos)
  return instruction_infos_.Get(index);
}
inline ::xla::HloProfilePrinterData_HloInstructionInfo* HloProfilePrinterData_HloComputationInfo::add_instruction_infos() {
  // @@protoc_insertion_point(field_add:xla.HloProfilePrinterData.HloComputationInfo.instruction_infos)
  return instruction_infos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloInstructionInfo >&
HloProfilePrinterData_HloComputationInfo::instruction_infos() const {
  // @@protoc_insertion_point(field_list:xla.HloProfilePrinterData.HloComputationInfo.instruction_infos)
  return instruction_infos_;
}

// -------------------------------------------------------------------

// HloProfilePrinterData

// repeated .xla.HloProfilePrinterData.HloComputationInfo computation_infos = 1;
inline int HloProfilePrinterData::computation_infos_size() const {
  return computation_infos_.size();
}
inline void HloProfilePrinterData::clear_computation_infos() {
  computation_infos_.Clear();
}
inline ::xla::HloProfilePrinterData_HloComputationInfo* HloProfilePrinterData::mutable_computation_infos(int index) {
  // @@protoc_insertion_point(field_mutable:xla.HloProfilePrinterData.computation_infos)
  return computation_infos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloComputationInfo >*
HloProfilePrinterData::mutable_computation_infos() {
  // @@protoc_insertion_point(field_mutable_list:xla.HloProfilePrinterData.computation_infos)
  return &computation_infos_;
}
inline const ::xla::HloProfilePrinterData_HloComputationInfo& HloProfilePrinterData::computation_infos(int index) const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.computation_infos)
  return computation_infos_.Get(index);
}
inline ::xla::HloProfilePrinterData_HloComputationInfo* HloProfilePrinterData::add_computation_infos() {
  // @@protoc_insertion_point(field_add:xla.HloProfilePrinterData.computation_infos)
  return computation_infos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::xla::HloProfilePrinterData_HloComputationInfo >&
HloProfilePrinterData::computation_infos() const {
  // @@protoc_insertion_point(field_list:xla.HloProfilePrinterData.computation_infos)
  return computation_infos_;
}

// int64 profile_counters_size = 2;
inline void HloProfilePrinterData::clear_profile_counters_size() {
  profile_counters_size_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 HloProfilePrinterData::profile_counters_size() const {
  // @@protoc_insertion_point(field_get:xla.HloProfilePrinterData.profile_counters_size)
  return profile_counters_size_;
}
inline void HloProfilePrinterData::set_profile_counters_size(::google::protobuf::int64 value) {
  
  profile_counters_size_ = value;
  // @@protoc_insertion_point(field_set:xla.HloProfilePrinterData.profile_counters_size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace xla

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fprofile_5fprinter_5fdata_2eproto_INCLUDED
