// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/verbs/verbs_service.proto

#ifndef PROTOBUF_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto_INCLUDED
#define PROTOBUF_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto_INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsChannelImpl();
void InitDefaultsChannel();
void InitDefaultsMemoryRegionImpl();
void InitDefaultsMemoryRegion();
void InitDefaultsGetRemoteAddressRequestImpl();
void InitDefaultsGetRemoteAddressRequest();
void InitDefaultsGetRemoteAddressResponseImpl();
void InitDefaultsGetRemoteAddressResponse();
void InitDefaultsErrorStatusProtoImpl();
void InitDefaultsErrorStatusProto();
inline void InitDefaults() {
  InitDefaultsChannel();
  InitDefaultsMemoryRegion();
  InitDefaultsGetRemoteAddressRequest();
  InitDefaultsGetRemoteAddressResponse();
  InitDefaultsErrorStatusProto();
}
}  // namespace protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto
namespace tensorflow {
class Channel;
class ChannelDefaultTypeInternal;
extern ChannelDefaultTypeInternal _Channel_default_instance_;
class ErrorStatusProto;
class ErrorStatusProtoDefaultTypeInternal;
extern ErrorStatusProtoDefaultTypeInternal _ErrorStatusProto_default_instance_;
class GetRemoteAddressRequest;
class GetRemoteAddressRequestDefaultTypeInternal;
extern GetRemoteAddressRequestDefaultTypeInternal _GetRemoteAddressRequest_default_instance_;
class GetRemoteAddressResponse;
class GetRemoteAddressResponseDefaultTypeInternal;
extern GetRemoteAddressResponseDefaultTypeInternal _GetRemoteAddressResponse_default_instance_;
class MemoryRegion;
class MemoryRegionDefaultTypeInternal;
extern MemoryRegionDefaultTypeInternal _MemoryRegion_default_instance_;
}  // namespace tensorflow
namespace google {
namespace protobuf {
template<> ::tensorflow::Channel* Arena::Create< ::tensorflow::Channel>(Arena*);
template<> ::tensorflow::ErrorStatusProto* Arena::Create< ::tensorflow::ErrorStatusProto>(Arena*);
template<> ::tensorflow::GetRemoteAddressRequest* Arena::Create< ::tensorflow::GetRemoteAddressRequest>(Arena*);
template<> ::tensorflow::GetRemoteAddressResponse* Arena::Create< ::tensorflow::GetRemoteAddressResponse>(Arena*);
template<> ::tensorflow::MemoryRegion* Arena::Create< ::tensorflow::MemoryRegion>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace tensorflow {

// ===================================================================

class Channel : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.Channel) */ {
 public:
  Channel();
  virtual ~Channel();

  Channel(const Channel& from);

  inline Channel& operator=(const Channel& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Channel(Channel&& from) noexcept
    : Channel() {
    *this = ::std::move(from);
  }

  inline Channel& operator=(Channel&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Channel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Channel* internal_default_instance() {
    return reinterpret_cast<const Channel*>(
               &_Channel_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Channel* other);
  friend void swap(Channel& a, Channel& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Channel* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<Channel>(NULL);
  }

  Channel* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<Channel>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Channel& from);
  void MergeFrom(const Channel& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Channel* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 lid = 1;
  void clear_lid();
  static const int kLidFieldNumber = 1;
  ::google::protobuf::int32 lid() const;
  void set_lid(::google::protobuf::int32 value);

  // int32 qpn = 2;
  void clear_qpn();
  static const int kQpnFieldNumber = 2;
  ::google::protobuf::int32 qpn() const;
  void set_qpn(::google::protobuf::int32 value);

  // uint64 snp = 4;
  void clear_snp();
  static const int kSnpFieldNumber = 4;
  ::google::protobuf::uint64 snp() const;
  void set_snp(::google::protobuf::uint64 value);

  // uint64 iid = 5;
  void clear_iid();
  static const int kIidFieldNumber = 5;
  ::google::protobuf::uint64 iid() const;
  void set_iid(::google::protobuf::uint64 value);

  // int32 psn = 3;
  void clear_psn();
  static const int kPsnFieldNumber = 3;
  ::google::protobuf::int32 psn() const;
  void set_psn(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tensorflow.Channel)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 lid_;
  ::google::protobuf::int32 qpn_;
  ::google::protobuf::uint64 snp_;
  ::google::protobuf::uint64 iid_;
  ::google::protobuf::int32 psn_;
  mutable int _cached_size_;
  friend struct ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::TableStruct;
  friend void ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::InitDefaultsChannelImpl();
};
// -------------------------------------------------------------------

class MemoryRegion : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.MemoryRegion) */ {
 public:
  MemoryRegion();
  virtual ~MemoryRegion();

  MemoryRegion(const MemoryRegion& from);

  inline MemoryRegion& operator=(const MemoryRegion& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MemoryRegion(MemoryRegion&& from) noexcept
    : MemoryRegion() {
    *this = ::std::move(from);
  }

  inline MemoryRegion& operator=(MemoryRegion&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MemoryRegion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MemoryRegion* internal_default_instance() {
    return reinterpret_cast<const MemoryRegion*>(
               &_MemoryRegion_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MemoryRegion* other);
  friend void swap(MemoryRegion& a, MemoryRegion& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MemoryRegion* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<MemoryRegion>(NULL);
  }

  MemoryRegion* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<MemoryRegion>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MemoryRegion& from);
  void MergeFrom(const MemoryRegion& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MemoryRegion* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 remote_addr = 1;
  void clear_remote_addr();
  static const int kRemoteAddrFieldNumber = 1;
  ::google::protobuf::uint64 remote_addr() const;
  void set_remote_addr(::google::protobuf::uint64 value);

  // uint32 rkey = 2;
  void clear_rkey();
  static const int kRkeyFieldNumber = 2;
  ::google::protobuf::uint32 rkey() const;
  void set_rkey(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tensorflow.MemoryRegion)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 remote_addr_;
  ::google::protobuf::uint32 rkey_;
  mutable int _cached_size_;
  friend struct ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::TableStruct;
  friend void ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::InitDefaultsMemoryRegionImpl();
};
// -------------------------------------------------------------------

class GetRemoteAddressRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.GetRemoteAddressRequest) */ {
 public:
  GetRemoteAddressRequest();
  virtual ~GetRemoteAddressRequest();

  GetRemoteAddressRequest(const GetRemoteAddressRequest& from);

  inline GetRemoteAddressRequest& operator=(const GetRemoteAddressRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetRemoteAddressRequest(GetRemoteAddressRequest&& from) noexcept
    : GetRemoteAddressRequest() {
    *this = ::std::move(from);
  }

  inline GetRemoteAddressRequest& operator=(GetRemoteAddressRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetRemoteAddressRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetRemoteAddressRequest* internal_default_instance() {
    return reinterpret_cast<const GetRemoteAddressRequest*>(
               &_GetRemoteAddressRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GetRemoteAddressRequest* other);
  friend void swap(GetRemoteAddressRequest& a, GetRemoteAddressRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetRemoteAddressRequest* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GetRemoteAddressRequest>(NULL);
  }

  GetRemoteAddressRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GetRemoteAddressRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetRemoteAddressRequest& from);
  void MergeFrom(const GetRemoteAddressRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetRemoteAddressRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tensorflow.MemoryRegion mr = 3;
  int mr_size() const;
  void clear_mr();
  static const int kMrFieldNumber = 3;
  ::tensorflow::MemoryRegion* mutable_mr(int index);
  ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion >*
      mutable_mr();
  const ::tensorflow::MemoryRegion& mr(int index) const;
  ::tensorflow::MemoryRegion* add_mr();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion >&
      mr() const;

  // string host_name = 1;
  void clear_host_name();
  static const int kHostNameFieldNumber = 1;
  const ::std::string& host_name() const;
  void set_host_name(const ::std::string& value);
  #if LANG_CXX11
  void set_host_name(::std::string&& value);
  #endif
  void set_host_name(const char* value);
  void set_host_name(const char* value, size_t size);
  ::std::string* mutable_host_name();
  ::std::string* release_host_name();
  void set_allocated_host_name(::std::string* host_name);

  // .tensorflow.Channel channel = 2;
  bool has_channel() const;
  void clear_channel();
  static const int kChannelFieldNumber = 2;
  const ::tensorflow::Channel& channel() const;
  ::tensorflow::Channel* release_channel();
  ::tensorflow::Channel* mutable_channel();
  void set_allocated_channel(::tensorflow::Channel* channel);

  // @@protoc_insertion_point(class_scope:tensorflow.GetRemoteAddressRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion > mr_;
  ::google::protobuf::internal::ArenaStringPtr host_name_;
  ::tensorflow::Channel* channel_;
  mutable int _cached_size_;
  friend struct ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::TableStruct;
  friend void ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::InitDefaultsGetRemoteAddressRequestImpl();
};
// -------------------------------------------------------------------

class GetRemoteAddressResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.GetRemoteAddressResponse) */ {
 public:
  GetRemoteAddressResponse();
  virtual ~GetRemoteAddressResponse();

  GetRemoteAddressResponse(const GetRemoteAddressResponse& from);

  inline GetRemoteAddressResponse& operator=(const GetRemoteAddressResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetRemoteAddressResponse(GetRemoteAddressResponse&& from) noexcept
    : GetRemoteAddressResponse() {
    *this = ::std::move(from);
  }

  inline GetRemoteAddressResponse& operator=(GetRemoteAddressResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetRemoteAddressResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetRemoteAddressResponse* internal_default_instance() {
    return reinterpret_cast<const GetRemoteAddressResponse*>(
               &_GetRemoteAddressResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GetRemoteAddressResponse* other);
  friend void swap(GetRemoteAddressResponse& a, GetRemoteAddressResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetRemoteAddressResponse* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GetRemoteAddressResponse>(NULL);
  }

  GetRemoteAddressResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<GetRemoteAddressResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetRemoteAddressResponse& from);
  void MergeFrom(const GetRemoteAddressResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetRemoteAddressResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tensorflow.MemoryRegion mr = 3;
  int mr_size() const;
  void clear_mr();
  static const int kMrFieldNumber = 3;
  ::tensorflow::MemoryRegion* mutable_mr(int index);
  ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion >*
      mutable_mr();
  const ::tensorflow::MemoryRegion& mr(int index) const;
  ::tensorflow::MemoryRegion* add_mr();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion >&
      mr() const;

  // string host_name = 1;
  void clear_host_name();
  static const int kHostNameFieldNumber = 1;
  const ::std::string& host_name() const;
  void set_host_name(const ::std::string& value);
  #if LANG_CXX11
  void set_host_name(::std::string&& value);
  #endif
  void set_host_name(const char* value);
  void set_host_name(const char* value, size_t size);
  ::std::string* mutable_host_name();
  ::std::string* release_host_name();
  void set_allocated_host_name(::std::string* host_name);

  // .tensorflow.Channel channel = 2;
  bool has_channel() const;
  void clear_channel();
  static const int kChannelFieldNumber = 2;
  const ::tensorflow::Channel& channel() const;
  ::tensorflow::Channel* release_channel();
  ::tensorflow::Channel* mutable_channel();
  void set_allocated_channel(::tensorflow::Channel* channel);

  // @@protoc_insertion_point(class_scope:tensorflow.GetRemoteAddressResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion > mr_;
  ::google::protobuf::internal::ArenaStringPtr host_name_;
  ::tensorflow::Channel* channel_;
  mutable int _cached_size_;
  friend struct ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::TableStruct;
  friend void ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::InitDefaultsGetRemoteAddressResponseImpl();
};
// -------------------------------------------------------------------

class ErrorStatusProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.ErrorStatusProto) */ {
 public:
  ErrorStatusProto();
  virtual ~ErrorStatusProto();

  ErrorStatusProto(const ErrorStatusProto& from);

  inline ErrorStatusProto& operator=(const ErrorStatusProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ErrorStatusProto(ErrorStatusProto&& from) noexcept
    : ErrorStatusProto() {
    *this = ::std::move(from);
  }

  inline ErrorStatusProto& operator=(ErrorStatusProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ErrorStatusProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ErrorStatusProto* internal_default_instance() {
    return reinterpret_cast<const ErrorStatusProto*>(
               &_ErrorStatusProto_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(ErrorStatusProto* other);
  friend void swap(ErrorStatusProto& a, ErrorStatusProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ErrorStatusProto* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ErrorStatusProto>(NULL);
  }

  ErrorStatusProto* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ErrorStatusProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ErrorStatusProto& from);
  void MergeFrom(const ErrorStatusProto& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ErrorStatusProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string error_message = 2;
  void clear_error_message();
  static const int kErrorMessageFieldNumber = 2;
  const ::std::string& error_message() const;
  void set_error_message(const ::std::string& value);
  #if LANG_CXX11
  void set_error_message(::std::string&& value);
  #endif
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  ::std::string* mutable_error_message();
  ::std::string* release_error_message();
  void set_allocated_error_message(::std::string* error_message);

  // string error_details = 3;
  void clear_error_details();
  static const int kErrorDetailsFieldNumber = 3;
  const ::std::string& error_details() const;
  void set_error_details(const ::std::string& value);
  #if LANG_CXX11
  void set_error_details(::std::string&& value);
  #endif
  void set_error_details(const char* value);
  void set_error_details(const char* value, size_t size);
  ::std::string* mutable_error_details();
  ::std::string* release_error_details();
  void set_allocated_error_details(::std::string* error_details);

  // int32 error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::google::protobuf::int32 error_code() const;
  void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tensorflow.ErrorStatusProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_message_;
  ::google::protobuf::internal::ArenaStringPtr error_details_;
  ::google::protobuf::int32 error_code_;
  mutable int _cached_size_;
  friend struct ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::TableStruct;
  friend void ::protobuf_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto::InitDefaultsErrorStatusProtoImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Channel

// int32 lid = 1;
inline void Channel::clear_lid() {
  lid_ = 0;
}
inline ::google::protobuf::int32 Channel::lid() const {
  // @@protoc_insertion_point(field_get:tensorflow.Channel.lid)
  return lid_;
}
inline void Channel::set_lid(::google::protobuf::int32 value) {
  
  lid_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.Channel.lid)
}

// int32 qpn = 2;
inline void Channel::clear_qpn() {
  qpn_ = 0;
}
inline ::google::protobuf::int32 Channel::qpn() const {
  // @@protoc_insertion_point(field_get:tensorflow.Channel.qpn)
  return qpn_;
}
inline void Channel::set_qpn(::google::protobuf::int32 value) {
  
  qpn_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.Channel.qpn)
}

// int32 psn = 3;
inline void Channel::clear_psn() {
  psn_ = 0;
}
inline ::google::protobuf::int32 Channel::psn() const {
  // @@protoc_insertion_point(field_get:tensorflow.Channel.psn)
  return psn_;
}
inline void Channel::set_psn(::google::protobuf::int32 value) {
  
  psn_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.Channel.psn)
}

// uint64 snp = 4;
inline void Channel::clear_snp() {
  snp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Channel::snp() const {
  // @@protoc_insertion_point(field_get:tensorflow.Channel.snp)
  return snp_;
}
inline void Channel::set_snp(::google::protobuf::uint64 value) {
  
  snp_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.Channel.snp)
}

// uint64 iid = 5;
inline void Channel::clear_iid() {
  iid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Channel::iid() const {
  // @@protoc_insertion_point(field_get:tensorflow.Channel.iid)
  return iid_;
}
inline void Channel::set_iid(::google::protobuf::uint64 value) {
  
  iid_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.Channel.iid)
}

// -------------------------------------------------------------------

// MemoryRegion

// uint64 remote_addr = 1;
inline void MemoryRegion::clear_remote_addr() {
  remote_addr_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MemoryRegion::remote_addr() const {
  // @@protoc_insertion_point(field_get:tensorflow.MemoryRegion.remote_addr)
  return remote_addr_;
}
inline void MemoryRegion::set_remote_addr(::google::protobuf::uint64 value) {
  
  remote_addr_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.MemoryRegion.remote_addr)
}

// uint32 rkey = 2;
inline void MemoryRegion::clear_rkey() {
  rkey_ = 0u;
}
inline ::google::protobuf::uint32 MemoryRegion::rkey() const {
  // @@protoc_insertion_point(field_get:tensorflow.MemoryRegion.rkey)
  return rkey_;
}
inline void MemoryRegion::set_rkey(::google::protobuf::uint32 value) {
  
  rkey_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.MemoryRegion.rkey)
}

// -------------------------------------------------------------------

// GetRemoteAddressRequest

// string host_name = 1;
inline void GetRemoteAddressRequest::clear_host_name() {
  host_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetRemoteAddressRequest::host_name() const {
  // @@protoc_insertion_point(field_get:tensorflow.GetRemoteAddressRequest.host_name)
  return host_name_.GetNoArena();
}
inline void GetRemoteAddressRequest::set_host_name(const ::std::string& value) {
  
  host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.GetRemoteAddressRequest.host_name)
}
#if LANG_CXX11
inline void GetRemoteAddressRequest::set_host_name(::std::string&& value) {
  
  host_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.GetRemoteAddressRequest.host_name)
}
#endif
inline void GetRemoteAddressRequest::set_host_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.GetRemoteAddressRequest.host_name)
}
inline void GetRemoteAddressRequest::set_host_name(const char* value, size_t size) {
  
  host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.GetRemoteAddressRequest.host_name)
}
inline ::std::string* GetRemoteAddressRequest::mutable_host_name() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.GetRemoteAddressRequest.host_name)
  return host_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetRemoteAddressRequest::release_host_name() {
  // @@protoc_insertion_point(field_release:tensorflow.GetRemoteAddressRequest.host_name)
  
  return host_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetRemoteAddressRequest::set_allocated_host_name(::std::string* host_name) {
  if (host_name != NULL) {
    
  } else {
    
  }
  host_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), host_name);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.GetRemoteAddressRequest.host_name)
}

// .tensorflow.Channel channel = 2;
inline bool GetRemoteAddressRequest::has_channel() const {
  return this != internal_default_instance() && channel_ != NULL;
}
inline void GetRemoteAddressRequest::clear_channel() {
  if (GetArenaNoVirtual() == NULL && channel_ != NULL) {
    delete channel_;
  }
  channel_ = NULL;
}
inline const ::tensorflow::Channel& GetRemoteAddressRequest::channel() const {
  const ::tensorflow::Channel* p = channel_;
  // @@protoc_insertion_point(field_get:tensorflow.GetRemoteAddressRequest.channel)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::Channel*>(
      &::tensorflow::_Channel_default_instance_);
}
inline ::tensorflow::Channel* GetRemoteAddressRequest::release_channel() {
  // @@protoc_insertion_point(field_release:tensorflow.GetRemoteAddressRequest.channel)
  
  ::tensorflow::Channel* temp = channel_;
  channel_ = NULL;
  return temp;
}
inline ::tensorflow::Channel* GetRemoteAddressRequest::mutable_channel() {
  
  if (channel_ == NULL) {
    channel_ = ::google::protobuf::Arena::Create< ::tensorflow::Channel >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.GetRemoteAddressRequest.channel)
  return channel_;
}
inline void GetRemoteAddressRequest::set_allocated_channel(::tensorflow::Channel* channel) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete channel_;
  }
  if (channel) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      channel = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, channel, submessage_arena);
    }
    
  } else {
    
  }
  channel_ = channel;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.GetRemoteAddressRequest.channel)
}

// repeated .tensorflow.MemoryRegion mr = 3;
inline int GetRemoteAddressRequest::mr_size() const {
  return mr_.size();
}
inline void GetRemoteAddressRequest::clear_mr() {
  mr_.Clear();
}
inline ::tensorflow::MemoryRegion* GetRemoteAddressRequest::mutable_mr(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.GetRemoteAddressRequest.mr)
  return mr_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion >*
GetRemoteAddressRequest::mutable_mr() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.GetRemoteAddressRequest.mr)
  return &mr_;
}
inline const ::tensorflow::MemoryRegion& GetRemoteAddressRequest::mr(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.GetRemoteAddressRequest.mr)
  return mr_.Get(index);
}
inline ::tensorflow::MemoryRegion* GetRemoteAddressRequest::add_mr() {
  // @@protoc_insertion_point(field_add:tensorflow.GetRemoteAddressRequest.mr)
  return mr_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion >&
GetRemoteAddressRequest::mr() const {
  // @@protoc_insertion_point(field_list:tensorflow.GetRemoteAddressRequest.mr)
  return mr_;
}

// -------------------------------------------------------------------

// GetRemoteAddressResponse

// string host_name = 1;
inline void GetRemoteAddressResponse::clear_host_name() {
  host_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetRemoteAddressResponse::host_name() const {
  // @@protoc_insertion_point(field_get:tensorflow.GetRemoteAddressResponse.host_name)
  return host_name_.GetNoArena();
}
inline void GetRemoteAddressResponse::set_host_name(const ::std::string& value) {
  
  host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.GetRemoteAddressResponse.host_name)
}
#if LANG_CXX11
inline void GetRemoteAddressResponse::set_host_name(::std::string&& value) {
  
  host_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.GetRemoteAddressResponse.host_name)
}
#endif
inline void GetRemoteAddressResponse::set_host_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.GetRemoteAddressResponse.host_name)
}
inline void GetRemoteAddressResponse::set_host_name(const char* value, size_t size) {
  
  host_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.GetRemoteAddressResponse.host_name)
}
inline ::std::string* GetRemoteAddressResponse::mutable_host_name() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.GetRemoteAddressResponse.host_name)
  return host_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetRemoteAddressResponse::release_host_name() {
  // @@protoc_insertion_point(field_release:tensorflow.GetRemoteAddressResponse.host_name)
  
  return host_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetRemoteAddressResponse::set_allocated_host_name(::std::string* host_name) {
  if (host_name != NULL) {
    
  } else {
    
  }
  host_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), host_name);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.GetRemoteAddressResponse.host_name)
}

// .tensorflow.Channel channel = 2;
inline bool GetRemoteAddressResponse::has_channel() const {
  return this != internal_default_instance() && channel_ != NULL;
}
inline void GetRemoteAddressResponse::clear_channel() {
  if (GetArenaNoVirtual() == NULL && channel_ != NULL) {
    delete channel_;
  }
  channel_ = NULL;
}
inline const ::tensorflow::Channel& GetRemoteAddressResponse::channel() const {
  const ::tensorflow::Channel* p = channel_;
  // @@protoc_insertion_point(field_get:tensorflow.GetRemoteAddressResponse.channel)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::Channel*>(
      &::tensorflow::_Channel_default_instance_);
}
inline ::tensorflow::Channel* GetRemoteAddressResponse::release_channel() {
  // @@protoc_insertion_point(field_release:tensorflow.GetRemoteAddressResponse.channel)
  
  ::tensorflow::Channel* temp = channel_;
  channel_ = NULL;
  return temp;
}
inline ::tensorflow::Channel* GetRemoteAddressResponse::mutable_channel() {
  
  if (channel_ == NULL) {
    channel_ = ::google::protobuf::Arena::Create< ::tensorflow::Channel >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.GetRemoteAddressResponse.channel)
  return channel_;
}
inline void GetRemoteAddressResponse::set_allocated_channel(::tensorflow::Channel* channel) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete channel_;
  }
  if (channel) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      channel = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, channel, submessage_arena);
    }
    
  } else {
    
  }
  channel_ = channel;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.GetRemoteAddressResponse.channel)
}

// repeated .tensorflow.MemoryRegion mr = 3;
inline int GetRemoteAddressResponse::mr_size() const {
  return mr_.size();
}
inline void GetRemoteAddressResponse::clear_mr() {
  mr_.Clear();
}
inline ::tensorflow::MemoryRegion* GetRemoteAddressResponse::mutable_mr(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.GetRemoteAddressResponse.mr)
  return mr_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion >*
GetRemoteAddressResponse::mutable_mr() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.GetRemoteAddressResponse.mr)
  return &mr_;
}
inline const ::tensorflow::MemoryRegion& GetRemoteAddressResponse::mr(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.GetRemoteAddressResponse.mr)
  return mr_.Get(index);
}
inline ::tensorflow::MemoryRegion* GetRemoteAddressResponse::add_mr() {
  // @@protoc_insertion_point(field_add:tensorflow.GetRemoteAddressResponse.mr)
  return mr_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::MemoryRegion >&
GetRemoteAddressResponse::mr() const {
  // @@protoc_insertion_point(field_list:tensorflow.GetRemoteAddressResponse.mr)
  return mr_;
}

// -------------------------------------------------------------------

// ErrorStatusProto

// int32 error_code = 1;
inline void ErrorStatusProto::clear_error_code() {
  error_code_ = 0;
}
inline ::google::protobuf::int32 ErrorStatusProto::error_code() const {
  // @@protoc_insertion_point(field_get:tensorflow.ErrorStatusProto.error_code)
  return error_code_;
}
inline void ErrorStatusProto::set_error_code(::google::protobuf::int32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ErrorStatusProto.error_code)
}

// string error_message = 2;
inline void ErrorStatusProto::clear_error_message() {
  error_message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ErrorStatusProto::error_message() const {
  // @@protoc_insertion_point(field_get:tensorflow.ErrorStatusProto.error_message)
  return error_message_.GetNoArena();
}
inline void ErrorStatusProto::set_error_message(const ::std::string& value) {
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.ErrorStatusProto.error_message)
}
#if LANG_CXX11
inline void ErrorStatusProto::set_error_message(::std::string&& value) {
  
  error_message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.ErrorStatusProto.error_message)
}
#endif
inline void ErrorStatusProto::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.ErrorStatusProto.error_message)
}
inline void ErrorStatusProto::set_error_message(const char* value, size_t size) {
  
  error_message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.ErrorStatusProto.error_message)
}
inline ::std::string* ErrorStatusProto::mutable_error_message() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.ErrorStatusProto.error_message)
  return error_message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ErrorStatusProto::release_error_message() {
  // @@protoc_insertion_point(field_release:tensorflow.ErrorStatusProto.error_message)
  
  return error_message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ErrorStatusProto::set_allocated_error_message(::std::string* error_message) {
  if (error_message != NULL) {
    
  } else {
    
  }
  error_message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_message);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.ErrorStatusProto.error_message)
}

// string error_details = 3;
inline void ErrorStatusProto::clear_error_details() {
  error_details_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ErrorStatusProto::error_details() const {
  // @@protoc_insertion_point(field_get:tensorflow.ErrorStatusProto.error_details)
  return error_details_.GetNoArena();
}
inline void ErrorStatusProto::set_error_details(const ::std::string& value) {
  
  error_details_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.ErrorStatusProto.error_details)
}
#if LANG_CXX11
inline void ErrorStatusProto::set_error_details(::std::string&& value) {
  
  error_details_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.ErrorStatusProto.error_details)
}
#endif
inline void ErrorStatusProto::set_error_details(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_details_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.ErrorStatusProto.error_details)
}
inline void ErrorStatusProto::set_error_details(const char* value, size_t size) {
  
  error_details_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.ErrorStatusProto.error_details)
}
inline ::std::string* ErrorStatusProto::mutable_error_details() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.ErrorStatusProto.error_details)
  return error_details_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ErrorStatusProto::release_error_details() {
  // @@protoc_insertion_point(field_release:tensorflow.ErrorStatusProto.error_details)
  
  return error_details_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ErrorStatusProto::set_allocated_error_details(::std::string* error_details) {
  if (error_details != NULL) {
    
  } else {
    
  }
  error_details_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error_details);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.ErrorStatusProto.error_details)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tensorflow_2fcontrib_2fverbs_2fverbs_5fservice_2eproto_INCLUDED
